// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQGuNih_0SptGPg9ezi_56gXj8KoJ2DzE',
    appId: '1:674437941938:web:83a64f6424e8356af357ab',
    messagingSenderId: '674437941938',
    projectId: 'domismart-c6054',
    authDomain: 'domismart-c6054.firebaseapp.com',
    storageBucket: 'domismart-c6054.firebasestorage.app',
    measurementId: 'G-L95TGP0ZW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2dpogLjGzq9fI2IXIW-htOT-PgSrA05g',
    appId: '1:674437941938:android:92ff7dddcc4c141df357ab',
    messagingSenderId: '674437941938',
    projectId: 'domismart-c6054',
    storageBucket: 'domismart-c6054.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyVxUa5oNohXjAmnGsfl_gn6ldv2q7hNE',
    appId: '1:674437941938:ios:1e220a7bd24fb7c4f357ab',
    messagingSenderId: '674437941938',
    projectId: 'domismart-c6054',
    storageBucket: 'domismart-c6054.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyVxUa5oNohXjAmnGsfl_gn6ldv2q7hNE',
    appId: '1:674437941938:ios:1e220a7bd24fb7c4f357ab',
    messagingSenderId: '674437941938',
    projectId: 'domismart-c6054',
    storageBucket: 'domismart-c6054.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQGuNih_0SptGPg9ezi_56gXj8KoJ2DzE',
    appId: '1:674437941938:web:3b4008f9bd0e6e99f357ab',
    messagingSenderId: '674437941938',
    projectId: 'domismart-c6054',
    authDomain: 'domismart-c6054.firebaseapp.com',
    storageBucket: 'domismart-c6054.firebasestorage.app',
    measurementId: 'G-NHQZRSRRKP',
  );
}
